(defun treemacs-on-current-project-exclusively (&optional arg)
  (interactive "P")
  (pcase (treemacs-current-visibility)
    ((guard arg)
     (treemacs-do-switch-workspace (treemacs--select-workspace-by-name))
     (treemacs-select-window))
    ('visible (delete-window (treemacs-get-local-window)))
    ('exists  (treemacs-display-current-project-exclusively))
    ('none    (treemacs-display-current-project-exclusively))))
