;;;; Meow configs

(defun meow-dv-arrow-setup ()
  (interactive)
  (setq meow-cheatsheet-layout meow-cheatsheet-layout-dvp)
  (meow-define-keys 'insert
    '("C-g" . meow-insert-exit))
  (meow-leader-define-key
   '("U" . find-file)
   '("?" . meow-cheatsheet))
  (meow-motion-overwrite-define-key
   ;; custom keybinding for motion state
   '("<escape>" . ignore))
  (meow-normal-define-key
   '("?" . meow-cheatsheet)
   '("*" . meow-expand-0)
   '("=" . meow-expand-9)
   '("!" . meow-expand-8)
   '("[" . meow-expand-7)
   '("]" . meow-expand-6)
   '("{" . meow-expand-5)
   '("+" . meow-expand-4)
   '("}" . meow-expand-3)
   '(")" . meow-expand-2)
   '("(" . meow-expand-1)
   '("1" . digit-argument)
   '("2" . digit-argument)
   '("3" . digit-argument)
   '("4" . digit-argument)
   '("5" . digit-argument)
   '("6" . digit-argument)
   '("7" . digit-argument)
   '("8" . digit-argument)
   '("9" . digit-argument)
   '("0" . digit-argument)
   '("-" . negative-argument)
   '(";" . meow-reverse)
   '("," . meow-inner-of-thing)
   '("." . meow-bounds-of-thing)
   '("<" . meow-beginning-of-thing)
   '(">" . meow-end-of-thing)
   '("a" . meow-append)
   '("A" . meow-open-below)
   '("b" . meow-back-word)
   '("B" . meow-back-symbol)
   '("C" . meow-change)
   '("d" . meow-delete)
   '("D" . meow-backward-delete)
   '("e" . meow-line)
   '("E" . meow-goto-line)
   '("f" . meow-find)
   '("g" . meow-cancel-selection)
   '("G" . meow-grab)
   '("h" . meow-left)
   '("H" . meow-left-expand)
   '("i" . meow-insert)
   '("I" . meow-open-above)
   '("j" . meow-join)
   '("k" . meow-kill)
   '("l" . meow-till)
   '("m" . meow-mark-word)
   '("M" . meow-mark-symbol)
   '("t" . meow-next)
   '("T" . meow-next-expand)
   '("o" . meow-block)
   '("O" . meow-to-block)
   '("c" . meow-prev)
   '("P" . meow-prev-expand)
   '("r" . meow-replace)
   '("R" . meow-swap-grab)
   '("s" . meow-search)
   '("n" . meow-right)
   '("N" . meow-right-expand)
   '("u" . meow-undo)
   '("U" . meow-undo-in-selection)
   '("v" . meow-visit)
   '("/" . meow-visit)
   '("w" . meow-next-word)
   '("W" . meow-next-symbol)
   '("x" . meow-save)
   '("X" . meow-sync-grab)
   '("y" . meow-yank)
   '("p" . yank)
   '("z" . meow-pop-selection)
   '("C-r" . helm-slime-repl-history)
   '("'" . repeat)
   '("=" . meow-indent)
   '("-" . meow-comment)
   '("<escape>" . ignore)))

(use-package meow
  :ensure t
  :bind
  ("C-c e n" . 'meow-normal-mode)
  ("C-c e m" . 'meow-motion-mode)
  :config
  (meow-dv-arrow-setup)
  (meow-global-mode 1)
  :custom
  (meow-use-clipboard t)
  (meow-expand-hint-remove-delay 0)
  (meow-keypad-ctrl-meta-prefix nil))

(provide 'init-meow)
